import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderOverlay from "./component/HeaderOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[520px]`}
      >
        <div className="bg-black/60 rounded p-2 relative flex flex-col h-full">
          {/* Sticky header */}
          <div className="sticky top-0 z-50">
            <HeaderOverlay />
          </div>

          {/* Scrollable content below header */}
          <div className="flex-1 overflow-auto min-h-[462px] w-full border-black border-2 box-border ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
