"use client";

import { useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [draggable, setDraggable] = useState(true);

  const handleClose = () => {
    window.electronAPI?.closeWindow();
  };

  const toggleDraggable = () => {
    setDraggable(!draggable);
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen bg-black/20`}
      >
        {/* Overlay Header / Navigation */}
        <div
          className="w-full h-10 flex items-center justify-between px-2"
          style={{ WebkitAppRegion: draggable ? "drag" : "no-drag" } as any}
        >
          <span className="text-white font-bold">Overlay App</span>

          {/* Buttons must be non-draggable */}
          <div
            className="flex space-x-2"
            style={{ WebkitAppRegion: "no-drag" } as any}
          >
            <button
              className="px-2 py-1 bg-blue-500 hover:bg-blue-400 text-white rounded"
              onClick={toggleDraggable}
            >
              {draggable ? "Lock Drag" : "Enable Drag"}
            </button>

            <button
              className="px-2 py-1 bg-red-500 hover:bg-red-400 text-white rounded"
              onClick={handleClose}
            >
              Exit
            </button>
          </div>
        </div>

        {/* Dynamic page content */}
        <div className="mt-4">{children}</div>
      </body>
    </html>
  );
}
