import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderOverlay from "./component/HeaderOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[520px] overflow-hidden`}
      >
        {/* Main Wrapper: flex-col ensures header and content stack correctly */}
        <div className="bg-white/50 rounded p-2 flex flex-col h-full border border-black/10">
          {/* DRAG AREA: This container holds your HeaderOverlay. 
              Because HeaderOverlay has WebkitAppRegion: "drag", 
              this entire top section acts as the window handle.
          */}
          <div className="shrink-0 h-8 bg-black">
            <HeaderOverlay />
          </div>

          {/* CONTENT AREA: flex-1 takes up remaining space.
              overflow-auto allows the page content to scroll 
              WITHOUT moving the HeaderOverlay.
          */}
          <main className="flex-1 overflow-auto bg-white/20 border-black/10 border-2 box-border rounded-sm">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
